name: AdvancedHopper
version: 1.1.0
main: me.letscode.minecraft.advanced_hopper.AdvancedHopperPlugin

author: LetsCode
description: "Minecraft plugin implementing an advanced filter hopper"
api-version: "1.20"
load: STARTUP

website: https://github.com/TheCodingEngineer/AdvancedHopperPlugin